# Generated by Django 5.1.3 on 2024-12-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Eventp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название мероприятия')),
                ('name', models.CharField(max_length=30, verbose_name='Введите ваше имя')),
                ('price', models.CharField(max_length=30, verbose_name='Цена мероприятия')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('adress', models.CharField(max_length=80, verbose_name='адресс')),
                ('date', models.CharField(max_length=30, verbose_name='Дата проведения')),
                ('phone', models.CharField(max_length=14, verbose_name='Номер для связи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ef_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
