# Generated by Django 5.1.3 on 2024-12-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ef_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Картинка мероприятия'),
        ),
    ]
