# Generated by Django 5.1.3 on 2024-12-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ef_app', '0002_eventp_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventp',
            new_name='Public',
        ),
    ]
