# Generated by Django 5.1.3 on 2024-12-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ef_app', '0003_rename_eventp_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='discription',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
    ]
