# Generated by Django 5.1.3 on 2024-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ef_app', '0004_alter_public_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='discription',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
